### ISSUE TITLE
xor issue

### ISSUE THREAD

**Issue by Doubleendedqueue** [HCDevelopers/MultiEncoder#4]
Encodings/encryptions (type "-i name" to get a description): xor
Encode (e) or decode (d)? e
Text: Hello

Key for xor (type "-gen" to generate): Uqco5LYByV
xor: -      

Result: -

**Comment by AnimeshShaw** [comment]
I tested the code it works correctly. 

![http://i.imgur.com/038c5Ro.png](http://i.imgur.com/038c5Ro.png)

**Comment by AnimeshShaw** [comment]
Ok I have figured out the solution.

**Comment by AnimeshShaw** [comment]
I have pulled a request. Please check. It should be solved by now. The problem was that the encoded characters had '\t' or other escape sequences and which were being executed when you were about to print something. 

But now that problem should be resolved.

See the Pull Request : https://github.com/HCDevelopers/MultiEncoder/pull/5

**Comment by AnimeshShaw** [comment]
The problem has been completely solved now. The generated result had escape sequences and so we have a problem. But now the results will fine. Also I added that the final result is to be written in "" and ask the user to copy the complete text within the quotes and that will solve the problem. This is will be beneficial not just in my case but in all the cases which may arise due to other encoding.

**Comment by Doubleendedqueue** [comment]
Thanks for fixing.

**Comment by Doubleendedqueue** [comment]
Encodings/encryptions (type "-i name" to get a description): xor
Encode (e) or decode (d)? d
Text: uXQQR\x11\x1dIXNI

Key for xor (type "-gen" to generate): 8fhTY1UlIG
Traceback (most recent call last):
  File "multiencoder.py", line 141, in <module>
    main()
  File "multiencoder.py", line 55, in main
    en_de_code(is_decode, text, algorithms)
  File "multiencoder.py", line 108, in en_de_code
    text = function(text, key)
  File "/home/deque/git/multiencoder/hcdev/encryptions/xor.py", line 26, in decode
    plain = self.XORencrypt(eval(ciphertext), key)
  File "<string>", line 1
    uXQQR\x11\x1dIXNI
                    ^
SyntaxError: unexpected character after line continuation character

Is there any possibility to make this work without having to put the '' there too?
I think it is unintuitive.
It works fine with the quotes, tough.

**Comment by AnimeshShaw** [comment]
I will try something else.
